In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# format for floats
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
df_survey = pd.read_csv('survey.csv', index_col='Timestamp')

df_survey.tail()

,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
Timestamp,,,,,,,,,,,,,,,,,,,,,
2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,No,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,Yes,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,No,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,Yes,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,No,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [3]:
df_survey = df_survey.drop('comments', axis=1)

In [4]:
df_tech_survey = df_survey[df_survey.tech_company != 'No']

In [5]:
df_tech_survey.iloc[:,: 12]

,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits
Timestamp,,,,,,,,,,,,
2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,No,Yes,Yes
2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,No,Yes,No
2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,No,Yes,No
2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,Yes,Yes,Yes
2014-08-27 11:31:22,33,Male,United States,TN,NaN,Yes,No,Sometimes,6-25,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
2015-08-20 16:52:09,29,male,United States,NC,No,Yes,Yes,Sometimes,100-500,Yes,Yes,Yes
2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,No,Yes,No
2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,Yes,Yes,Yes
2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes
2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,Yes,Yes,No

In [6]:
df_tech_survey.drop(df_tech_survey[df_tech_survey['Age'] >= 90].index, inplace = True)

/opt/homebrew/Caskroom/miniforge/base/envs/CIS4930/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [7]:
df_tech_survey.drop(df_tech_survey[df_tech_survey['Age'] < 18].index, inplace = True)

In [8]:
binary_genders = ['Male', 'Female']
df_tech_survey.loc[df_tech_survey['Gender'].str.lower().str.startswith('f'), 'Gender'] = 'Female'
df_tech_survey.loc[df_tech_survey['Gender'].str.lower().str.startswith('m'), 'Gender'] = 'Male'
df_tech_survey.loc[~df_tech_survey['Gender'].isin(binary_genders), 'Gender'] = 'Other'

/opt/homebrew/Caskroom/miniforge/base/envs/CIS4930/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [9]:
df_tech_survey.drop('no_employees', axis=1)

,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
Timestamp,,,,,,,,,,,,,,,,,,,,,
2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
2014-08-27 11:31:22,33,Male,United States,TN,NaN,Yes,No,Sometimes,No,Yes,...,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-08-20 16:52:09,29,Male,United States,NC,No,Yes,Yes,Sometimes,Yes,Yes,...,Yes,Don't know,Yes,No,Some of them,No,No,Maybe,No,No
2015-09-12 11:17:21,26,Male,United Kingdom,NaN,No,No,Yes,NaN,No,Yes,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
2015-11-07 12:36:58,34,Male,United States,CA,No,Yes,Yes,Sometimes,No,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
2015-11-30 21:25:06,46,Female,United States,NC,No,No,No,NaN,Yes,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No

In [10]:
csv_data = df_tech_survey.to_csv('Clean Mental Health Survey Data.csv', index=True)